services:
  insider-db:
    image: postgres:16.1
    container_name: insiderDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=insider
      - POSTGRES_USER=insider
      - POSTGRES_PASSWORD=insider
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
