services:
  postgres-db:
    image: postgres:16.1
    container_name: postgresDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=game
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  redis-db:
    image: redis
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data

  game-service:
    build: /server
    container_name: game-service
    ports:
      - "9090:9090"
    depends_on:
      - postgres-db
      - redis-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/game
      - SPRING_DATASOURCE_USERNAME=game
      - SPRING_DATASOURCE_PASSWORD=game
      - SPRING_REDIS_HOST=http://redis-db
      - SPRING_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis

  game-gateway:
    build: /gateway
    container_name: game-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis-db
    environment:
      - GAME_SERVER_URL=http://game-service:9090