services:
  postgres-db:
    image: postgres:16.1
    container_name: postgresDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=game
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=game
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data

  game-service:
    build: /
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/game
      - SPRING_DATASOURCE_USERNAME=game
      - SPRING_DATASOURCE_PASSWORD=game
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
