server:
  undertow:
    max-http-post-size: 10KB
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: game
    password: game
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      mode: always
