server:
  undertow:
    max-http-post-size: 10KB
  port: 9090

spring:
  data:
    redis:
      host: redis-db
      port: 6379
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: game
    password: game
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      mode: always


logging:
  level:
    io.lettuce.core: DEBUG