create table IF NOT EXISTS users (
id bigint generated by default as identity,
first_name varchar(255) not null,
last_name varchar(255) not null,
joined_company date not null,
primary key (id),
unique (first_name, last_name, joined_company)
);