create table IF NOT EXISTS user_credentials (
id bigint generated by default as identity,
email varchar(255) not null,
password varchar(255) not null,
role varchar(255) check (role in ('ADMIN','MANAGER')),
user_id bigint not null references users(id),
primary key (id),
unique (email, password, role)
);