CREATE TABLE IF NOT EXISTS user_activity_data (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_uuid uuid NOT NULL,
    create_activity timestamp not null,
    activity bigint NOT NULL,
    PRIMARY KEY (id),
    unique(user_uuid, create_activity, activity)
);